sudo: required

services:
  - docker

before_install:
  - docker build --tag smonn/docker-react --file Dockerfile.dev .

script:
  - docker run --env CI=true smonn/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-production"
  bucket_name: "elasticbeanstalk-us-east-1-259347196174"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
